from math import *
name = input('Введите имя и фамилию ученика : ')
marks = input('Введите его оценки за контрольные и самостоятельные : ')
marks_1 = list(marks)
new_marks = input('Введите оценки за работу на уроках : ')
marks_1.extend(new_marks)
marks_1.sort()
marks_1.insert(0, name)
marks_1.insert(1, ':')
one = marks_1.count('1')
two = marks_1.count('2')
thr = marks_1.count('3')
fou = marks_1.count('4')
fiv = marks_1.count('5')
marks_1 = str(marks_1)
marks_1 = marks_1.replace('[', '')
marks_1 = marks_1.replace(']', '')
marks_1 = marks_1.replace("'", '')
marks_1 = marks_1.replace(',', '')
all_2 = (one + two + thr + fou + fiv)
all_1 = (one * 1 + two * 2 + thr * 3 + fou * 4 + fiv * 5)
srednee = ceil(all_1 / all_2)
print('Итоги работы ученика за четверть :')
print(marks_1)
print('Оценка за четверть :', srednee)

